expireTime: 6 #Optional, default is 30, number of days. clean up all history in the database before this number of days

userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36 # Optional, user agent to send to the rss feed

flaresolverr: http://127.0.0.1:8191/ # Optional, default is empty, used to solve cloudflare challenge, refer to https://github.com/FlareSolverr/FlareSolverr

notifyTelegramChatId: 111111111 # Optional, if empty, telegram notification for expired links will be disabled

proxy: # Optional, if empty, proxy will be disabled
  enabled: true # Optional, default is false
  protocol: socks5 # Optional, default is http, can be http or socks5
  host: 192.168.1.33 # Optional, default is 127.0.0.1
  port: 50004 # Optional, default is 1080
  auth: # Optional, if empty, no auth will be used
    username: test # Optional, default is empty
    password: test # Optional, default is empty

telegram: # Required, at least one telegram bot is required
  - name: default # Required, name of the telegram bot
    token: test123 # Required, token of the telegram bot
    chatId: 12345 # Required, chat id of the telegram bot
    parseMode: MarkdownV2 # Optional, default is Markdown, can be HTML, Markdown or MarkdownV2
    disableNotification: false # Optional, default is false, if true, telegram notification will be disabled
    disableWebPagePreview: false # Optional, default is false, if true, telegram web page preview will be disabled
